# 文档解析自动化Agent配置
name: parse_documents_agent
description: Automated document parsing agent for extracting knowledge from files
version: 1.0.0
author: System Administrator
created: 2025-11-06
updated: 2025-11-06

# ==================== 基础配置 ====================
config:
  # 数据库配置
  database:
    path: "knowledge_base.db"
    connection_timeout: 30
    max_connections: 5

  # 执行配置
  execution:
    default_interval_minutes: 30
    max_retry_attempts: 3
    retry_delay_seconds: 60
    batch_size: 50
    timeout_seconds: 600

  # 解析配置
  parsing:
    supported_formats: ['.pdf', '.xlsx', '.xls', '.docx', '.doc', '.txt', '.csv']
    confidence_threshold: 0.7
    max_file_size_mb: 50
    encoding: 'utf-8'

# ==================== Agent Triggers ====================
triggers:
  # 文件系统监控触发器
  file_system_monitor:
    - name: inquiry_files_monitor
      description: "监控询价文件夹中的新文件"
      directories:
        - "/Users/gavin/Nutstore Files/.symlinks/坚果云/005-询盘询价和/"
        - "/Users/gavin/Nutstore Files/.symlinks/坚果云/002-客户中/"
      events:
        - "file_added"
        - "directory_created"
      file_patterns:
        - "*.pdf"
        - "*.xlsx"
        - "*.xls"
        - "*.docx"
        - "*.doc"
        - "*.txt"
        - "*.csv"
      enabled: true
      priority: 1

    - name: customer_files_monitor
      description: "监控客户文件夹中的新文件"
      directories:
        - "/Users/gavin/Nutstore Files/.symlinks/坚果云/002-客户中/"
      events:
        - "file_added"
        - "directory_created"
      file_patterns:
        - "*.pdf"
        - "*.xlsx"
        - "*.xls"
        - "*.docx"
        - "*.doc"
      enabled: true
      priority: 2

  # 定时扫描触发器
  scheduled_scan:
    - name: hourly_scan
      description: "每小时扫描指定目录中的文件"
      cron: "0 * * * *"  # 每小时执行
      timezone: "Asia/Shanghai"
      directories:
        - "/Users/gavin/Nutstore Files/.symlinks/坚果云/005-询盘询价和/"
        - "/Users/gavin/Nutstore Files/.symlinks/坚果云/002-客户中/"
      file_patterns:
        - "*.pdf"
        - "*.xlsx"
        - "*.xls"
        - "*.docx"
        - "*.doc"
      enabled: true
      priority: 3

# ==================== Agent Actions ====================
actions:
  primary:
    - name: parse_new_documents
      description: "Parse newly detected documents"
      command: "python3 parse_documents.py --mode batch"
      working_directory: "/Users/gavin/Knowledge base"
      timeout: 600  # 10 minutes
      retry_count: 3
      retry_delay: 120  # 2 minutes
      batch_size: 10

    - name: process_single_document
      description: "Process a single document file"
      command: "python3 parse_documents.py --mode single --file"
      working_directory: "/Users/gavin/Knowledge base"
      timeout: 120  # 2 minutes
      retry_count: 2
      retry_delay: 30  # 30 seconds

  secondary:
    - name: update_file_index
      description: "Update file processing index"
      command: "python3 update_file_index.py"
      working_directory: "/Users/gavin/Knowledge base"
      timeout: 180
      condition: "processed_count > 0"

    - name: generate_parsing_report
      description: "Generate daily parsing report"
      command: "python3 generate_parsing_report.py"
      working_directory: "/Users/gavin/Knowledge base"
      timeout: 120
      schedule: "0 18 * * *"  # 每天18:00执行

    - name: cleanup_processed_files
      description: "Clean up old processed data"
      command: "python3 cleanup_parsed_data.py"
      working_directory: "/Users/gavin/Knowledge base"
      timeout: 60
      schedule: "0 2 * * 0"  # 每周日凌晨2点

# ==================== 解析规则配置 ====================
parsing_rules:
  # 客户信息提取规则
  customer_extraction:
    patterns:
      - type: "company_name"
        regex_patterns:
          - "(?i)(公司|有限公司|股份公司|企业|实业|科技|制造)"
        confidence_threshold: 0.8
        context_window: 50
      - type: "contact_person"
        regex_patterns:
          - "(?i)(经理|主管|负责人|先生|女士)"
        confidence_threshold: 0.7
        context_window: 30
      - type: "phone_number"
        regex_patterns:
          - "1[3-9]\\d{9}"
          - "\\d{3}-\\d{4}-\\d{4}"
        confidence_threshold: 0.9
      - type: "email"
        regex_patterns:
          - "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"
        confidence_threshold: 0.95

  # 产品信息提取规则
  product_extraction:
    patterns:
      - type: "product_name"
        keywords: ["螺栓", "螺钉", "螺丝", "紧固件", "垫片", "轴承"]
        confidence_threshold: 0.8
      - type: "specification"
        regex_patterns:
          - "M\\d+"
          - "\\d+\\s*mm"
          - "φ\\d+"
        confidence_threshold: 0.7
      - type: "material"
        keywords: ["不锈钢", "碳钢", "合金钢", "铜", "铝", "锌", "尼龙"]
        confidence_threshold: 0.8
      - type: "quantity"
        regex_patterns:
          - "\\d+\\s*(个|件|套|箱|包)"
          - "(?i)quantity"
        confidence_threshold: 0.8

  # 价格信息提取规则
  price_extraction:
    patterns:
      - type: "unit_price"
        regex_patterns:
          - "￥\\s*\\d+\\.?\\d*"
          - "RMB\\s*\\d+\\.?\\d*"
          - "\\$\\s*\\d+\\.?\\d*"
        confidence_threshold: 0.8
      - type: "total_price"
        regex_patterns:
          - "总价\\s*[：:]?\\s*\\d+\\.?\\d*"
          - "合计\\s*[：:]?\\s*\\d+\\.?\\d*"
        confidence_threshold: 0.7
      - type: "currency"
        keywords: ["元", "美元", "EUR", "USD", "RMB", "CNY"]
        confidence_threshold: 0.9

# ==================== 输出配置 ====================
output:
  # 数据库存储
  database:
    enabled: true
    table: "knowledge_entries"

  # JSON文件存储
  json_files:
    enabled: true
    directory: "./data/processed"
    filename_pattern: "parsed_docs_{date}.json"
    max_file_size: "10MB"

  # 日志记录
  logging:
    enabled: true
    file_path: "./data/processed/parse_documents_agent.log"
    max_file_size: "50MB"
    log_level: "INFO"
    format: "json"

# ==================== 错误处理和重试策略 ====================
error_handling:
  max_retries: 3
  retry_delay:
    initial: 30  # seconds
    max: 300     # 5 minutes
    backoff_factor: 2

  error_notifications:
    enabled: true
    recipients:
      - "admin@company.com"
    subject_prefix: "[Document Parser Alert]"

  critical_errors:
    - "file_access_denied"
    - "parsing_engine_failed"
    - "database_connection_failed"
    - "memory_limit_exceeded"

  retry_on_errors:
    - "timeout"
    - "file_busy"
    - "temporary_unavailable"
    - "network_error"

# ==================== 工具权限配置 ====================
tools_allowed:
  FileSystem:
    permissions: ["Read", "Write"]
    allowed_paths:
      - "/Users/gavin/Nutstore Files/.symlinks/坚果云/"
      - "/Users/gavin/Knowledge base/data"
      - "/Users/gavin/Knowledge base/data/processed"

  PythonExecution:
    allowed_scripts:
      - "parse_documents.py"
      - "update_file_index.py"
      "generate_parsing_report.py"
      "cleanup_parsed_data.py"
    sandbox_enabled: true
    max_execution_time: 600  # 10 minutes

  TextProcessing:
    enabled: true
    libraries:
      - "pdfplumber"
      - "openpyxl"
      - "python-docx"
      - "pandas"
      - "re"
      - "jieba"  # 中文分词

# ==================== 资源限制 ====================
resources:
  max_memory: "1GB"
  max_cpu_time: 600  # 10 minutes per execution
  max_concurrent_actions: 3
  max_file_size: "100MB"